---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "RelEng SlaveHealth"
consumes:
  - application/json
produces:
  - application/json
paths:

  /slaves:
    get:
      operationId: "releng_slavehealth.api.all_slaves"
      responses:
        200:
          description: Trees
          schema: 
            type: array
            items: 
              type: array
              item:
                type: string
